// <auto-generated />
using System;
using KaseyWebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KaseyWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220629195642_UpdateDB1")]
    partial class UpdateDB1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KaseyWebApi.DataModel.Link", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("links");

                    b.HasData(
                        new
                        {
                            Id = "95a0a383-eab3-442e-8dda-336f930426f2",
                            CreatedAt = "6/29/2022 2:56:42 PM",
                            Description = "Search Engine",
                            LinkUrl = "https://google.com",
                            Topic = "Learning"
                        });
                });

            modelBuilder.Entity("KaseyWebApi.DataModel.UserInfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("userInfo");

                    b.HasData(
                        new
                        {
                            UserId = 7,
                            CreatedDate = new DateTime(2022, 6, 29, 19, 56, 42, 249, DateTimeKind.Utc).AddTicks(3440),
                            DisplayName = "KPC",
                            Email = "kaseypaulcantu@gmail.com",
                            Password = "password321",
                            UserName = "KaseyPCantu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
