// <auto-generated />
using System;
using KaseyWebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KaseyWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220629202831_AddedEmployeeSchema")]
    partial class AddedEmployeeSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KaseyWebApi.DataModel.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<string>("LoginId")
                        .HasColumnType("text");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NationalIdNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("RowGuid")
                        .HasColumnType("uuid");

                    b.Property<short>("SickLeaveHours")
                        .HasColumnType("smallint");

                    b.Property<short>("VacationHours")
                        .HasColumnType("smallint");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 9,
                            BirthDate = new DateTime(1993, 6, 22, 5, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeName = "Kasey Cantu",
                            Gender = "M",
                            HireDate = new DateTime(2018, 8, 9, 5, 0, 0, 0, DateTimeKind.Utc),
                            JobTitle = "Software Engieer",
                            LoginId = "shipengine-kasey",
                            MaritalStatus = "M",
                            ModifiedDate = new DateTime(2022, 5, 27, 5, 0, 0, 0, DateTimeKind.Utc),
                            NationalIdNumber = "8989898989898989",
                            RowGuid = new Guid("31001f30-95a6-4e1c-8004-ea7521c2323a"),
                            SickLeaveHours = (short)300,
                            VacationHours = (short)500
                        });
                });

            modelBuilder.Entity("KaseyWebApi.DataModel.Link", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("links");

                    b.HasData(
                        new
                        {
                            Id = "5c1ee9c7-3174-4d2b-8980-4643e3714379",
                            CreatedAt = "6/29/2022 3:28:31 PM",
                            Description = "Search Engine",
                            LinkUrl = "https://google.com",
                            Topic = "Learning"
                        });
                });

            modelBuilder.Entity("KaseyWebApi.DataModel.UserInfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("userInfo");

                    b.HasData(
                        new
                        {
                            UserId = 7,
                            CreatedDate = new DateTime(2022, 6, 29, 20, 28, 31, 446, DateTimeKind.Utc).AddTicks(2480),
                            DisplayName = "KPC",
                            Email = "kaseypaulcantu@gmail.com",
                            Password = "password321",
                            UserName = "KaseyPCantu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
